# Generated by Django 5.2.3 on 2025-06-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='max_students',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lessons_count',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='start_date',
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
