services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB:       coursesdb
      POSTGRES_USER:     user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./courses-api-backend
    # mount your local code, so `runserver` will reload on file changes
    volumes:
      - ./courses-api-backend:/app
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8008
    environment:
      POSTGRES_DB:       coursesdb
      POSTGRES_USER:     user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST:     db
      POSTGRES_PORT:     5432
    ports:
      - "8008:8008"
    depends_on:
      - db

  frontend:
    build: ./courses-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
